# --- File Inclusion/Exclusion Configuration ---

# Files and patterns to include in the snapshot.
GLOB_INCLUDE = [
    "*.go",
    "*.json",
    "Gopkg.toml",
    "Gopkg.lock",
    "Makefile",
    "*.tmpl",
    "*.gohtml",
    "*.proto",
    "*.openapi.yaml",
    "*.py",
    "pyproject.toml",
    "setup.cfg",
    "setup.py",
    "poetry.lock",
    "requirements*.txt",
    "tox.ini",
    "migrations/**/*.py",
    "*.css",
    "*.scss",
    "*.sass",
    "*.js",
    "*.jsx",
    "*.ts",
    "*.tsx",
    "*.vue",
    "*.hcl",
    "*.yml",
    "*.yaml",
    "pnpm-lock.yaml",
    "yarn.lock",
    "vite.config.*",
    "nuxt.config.*",
    ".eslintrc*",
    ".prettierrc*",
    ".babelrc*",
    "*.cs",
    "*.csproj",
    "*.sln",
    "*.cshtml",
    "*.razor",
    "*.flow",
    "*.config",
    ".dockerignore",
    "*Dockerfile*",
    "docker-compose*.yml",
    "Procfile",
    ".pre-commit-config.yaml",
    ".github/**/*.yml",
    ".gitlab-ci.yml",
    "azure-pipelines.yml",
    "*.md",
    "CONTRIBUTING*.md",
    "docs/**/*.{md,mdx}",
    "tests/**/*.{py,js,ts,cs}",
    "*.ipynb",
    "schema/**/*.json",
]

# Directories to completely exclude from the search.
GLOB_EXCLUDE_DIRS = {
    ".git",
    "node_modules",
    "dist",
    "build",
    ".venv",
    "__pycache__",
    "bin",
    "obj",
    ".vs",
    ".vscode",
    "vendor",
    "_next"
}

# File name patterns to exclude.
EXCLUDE_FILE_PATTERNS = {
    "*.min.*",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.ico",
    "*.svg",
    "*.woff",
    "*.woff2",
    "*.ttf",
    "*.otf",
    "*.eot",
    "*.pdf",
    "*.doc",
    "*.docx",
    "*.xls",
    "*.xlsx",
    "*.zip",
    "*.tar*",
    "*.gz",
    "*.bz2",
    "*.rar",
    "*.7z",
    "*.nupkg",
    "*.snupkg",
    "*.dll",
    "*.pdb",
    "*.exe",
    "*.so",
    "*.dylib",
    "*.a",
    "*.o",
    "*lock.json",
    "pnpm-lock.yaml",
    "package-lock.json",
    "project.assets.json",
    "go.mod",
    "go.sum",
}

# Default maximum file size in kilobytes.
DEFAULT_SIZE_KB = 400
