alias ls='ls -F --color'
alias f=fabric.sh
alias k=kubectl
alias op-in='eval $(op signin my)'
alias op-out='op signout && unset OP_SESSION_my'
alias gcl='./node_modules/.bin/gitlab-ci-local'
alias pon='proxy_on'
alias poff='proxy_off'
alias git-set-ubisoft='git config user.name "Paul Cuciureanu"; git config user.email "paul.cuciureanu@ubisoft.com"'
alias git-unset='git config --unset user.name; git config --unset user.email'
alias gais='genaiscript'
alias gen='genaiscript run'
alias models="curl -s http://192.168.1.22:11434/api/tags | jq -r '.models[].name'"
alias rs=repo-sync.py