#!/usr/bin/env bash

HOST_SSH_DIR="/mnt/c/Users/pcuci/.ssh"
WSL_SSH_DIR="/home/paul/.ssh"

cp $WSL_SSH_DIR/id_* $HOST_SSH_DIR

chmod 600 $HOST_SSH_DIR/id_*
chmod g+r,o+r $HOST_SSH_DIR/*.pub

cp $WSL_SSH_DIR/config $HOST_SSH_DIR 
